language: python
python:
  - "3.10"
# Установка зависимостей
install:
  - pip install -r requirements/common.txt
# Команда для запуска тестов
script:
  - python manage.py test --settings=settings.env.test -v=2
