services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=db
      # - MYSQL_USER=user  # Не работает для 5.7
      # - MYSQL_PASSWORD=pass  # Не работает для 5.7
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash run.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.env.dev_docker
    depends_on:
      - db
