# Generated by Django 4.1 on 2024-11-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Id')),
                ('url', models.URLField(verbose_name='Url')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Id')),
                ('url', models.URLField(verbose_name='Url')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Id')),
                ('url', models.URLField(verbose_name='Url')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Ссылка на превью')),
                ('publish_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
