# Generated by Django 4.1 on 2024-11-09 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_playlist_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='youtube.channel', verbose_name='Канал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.playlist', verbose_name='Плейлист'),
        ),
    ]
