# Generated by Django 4.1 on 2024-11-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0001_initial'),
        ('youtube', '0005_alter_channel_options_alter_playlist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время просмотра')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_area.profile', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='viewed',
            field=models.ManyToManyField(blank=True, through='youtube.VideoView', to='personal_area.profile', verbose_name='Просмотрено'),
        ),
        migrations.AddField(
            model_name='videoview',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video', verbose_name='Пользователь'),
        ),
    ]
