# Generated by Django 4.1 on 2024-11-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_videoview_video_viewed_videoview_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на превью'),
        ),
    ]
