# Generated by Django 4.1 on 2024-11-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_channel_thumbnail_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='channel',
            name='last_update',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.URLField(help_text='URL адрес главной страницы канала', unique=True, verbose_name='Url'),
        ),
    ]
