# Generated by Django 4.1 on 2024-11-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_alter_video_options_channel_last_update_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoview',
            options={'verbose_name': 'Просмотр видео', 'verbose_name_plural': 'Просмотры видео'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
