# Generated by Django 2.0.7 on 2018-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0005_auto_20180722_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
