# Generated by Django 2.0.7 on 2018-08-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0007_auto_20180804_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_date',
            new_name='creation_date',
        ),
    ]
