# Generated by Django 2.1.3 on 2018-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
    ]
