# Generated by Django 2.2.1 on 2019-09-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0006_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Assay',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
