# Generated by Django 4.1 on 2025-01-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.TextField(blank=True, default='', verbose_name='Постер в Base64'),
            preserve_default=False,
        ),
    ]
